### PR TITLE
Tuner

### PR DESCRIPTION
**Pull request by andresmmera**
@tipofthesowrd I've been working on your tuner feature. I did some changes both in the UI and in the logic behind. Hope you don't mind.

Could you take a look at it? I've tested it throughly but surely some issue remain...
Hopefully we can merge https://github.com/Qucs/qucs/pull/471 in the next release.

Screencast: https://drive.google.com/open?id=0BwDjrwGfd_z7VlplN1kzMWRSNFk

### CODE REVIEW

**Comment by tipofthesowrd** [comment]
Looks very good, I'll see if I can finish up this merge request later this week /weekend

**Comment by andresmmera** [comment]
Uhm, If I remember correctly, the last time I saw this there was no conflicts with your branch...

**Comment by tipofthesowrd** [comment]
According to Github still some conflicting files

Conflicting files

qucs/qucs/bitmaps/tune.png
qucs/qucs/dialogs/simmessage.cpp
qucs/qucs/dialogs/tuner.cpp
qucs/qucs/dialogs/tuner.h
qucs/qucs/mouseactions.cpp
qucs/qucs/qucs.cpp
qucs/qucs/qucs.qrc

**Comment by andresmmera** [comment]
I think I spoke without thinking.
Please forget what I said... :-)

**Comment by andresmmera** [comment]
Thanks! :-)

**Comment by andresmmera** [comment]
No worries. I understand completely.
Lol, I was texting by the time I received the merge notification... so maybe I replied too fast :-)

**Pull request merged**
